// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class ValidarNuevoMSGTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver","src/main/resources/chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void validarNuevoMSG() {
    // Test name: Validar_NuevoMSG
    // Step # | name | target | value
    // 1 | open | http://automationpractice.com/index.php?controller=contact | 
    driver.get("http://automationpractice.com/index.php?controller=contact");
    // 2 | setWindowSize | 1382x744 | 
    driver.manage().window().setSize(new Dimension(1382, 744));
    // 3 | click | id=id_contact | 
    driver.findElement(By.id("id_contact")).click();
    // 4 | select | id=id_contact | label=Customer service
    {
      WebElement dropdown = driver.findElement(By.id("id_contact"));
      dropdown.findElement(By.xpath("//option[. = 'Customer service']")).click();
    }
    // 5 | click | id=id_contact | 
    driver.findElement(By.id("id_contact")).click();
    // 6 | click | id=email | 
    driver.findElement(By.id("email")).click();
    // 7 | click | id=message | 
    driver.findElement(By.id("message")).click();
    // 8 | type | id=message | Gracias por todo!!
    driver.findElement(By.id("message")).sendKeys("Gracias por todo!!");
    // 9 | click | css=#submitMessage > span | 
    driver.findElement(By.cssSelector("#submitMessage > span")).click();
  }
}
